name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Match Dockerfile
          extensions: mbstring, xml, pdo, pdo_pgsql, zip, bcmath # Add extensions needed by Laravel/tests
          coverage: none # Or pcov/xdebug if coverage needed

      - name: Copy .env
        run: php -r "file_exists('backend_laravel/.env') || copy('backend_laravel/.env.example', 'backend_laravel/.env');"
        working-directory: ${{ github.workspace }}

      - name: Install Dependencies (Laravel)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ${{ github.workspace }}/backend_laravel

      - name: Generate key (Laravel)
        run: php artisan key:generate
        working-directory: ${{ github.workspace }}/backend_laravel

      - name: Run Tests (Laravel)
        run: php artisan test
        working-directory: ${{ github.workspace }}/backend_laravel
        # Add environment variables needed for tests if any
        # env:
        #   DB_CONNECTION: sqlite
        #   DB_DATABASE: :memory:

  fastapi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Match Dockerfile

      - name: Install Dependencies (FastAPI)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Install pytest for running tests
        working-directory: ${{ github.workspace }}/backend_fastapi

      - name: Run Tests (FastAPI)
        run: pytest
        working-directory: ${{ github.workspace }}/backend_fastapi
        # Add environment variables needed for tests if any
        # env:
        #   DATABASE_URL: ...
